logging:
 config: 'classpath:logback.xml'

spring:
 profiles:
  active: local

camel:
  service:
    lra:
      enabled: true
      coordinator-url: http://192.168.2.106
      local-participant-url: http://192.168.2.106:8083/api
  component:
    servlet:
      mapping:
        context-path: /api/*

server:
  port: 8083
